export const LOCAL_STORAGE_KEY = "finance-dashboard-state-v4-2026-apr-02";
export const OPENING_BALANCE = 0;

export const ROLE_OPTIONS = [
  { value: "viewer", label: "Viewer" },
  { value: "admin", label: "Admin" },
];

export const CATEGORY_OPTIONS = [
  "Salary",
  "Freelance",
  "Housing",
  "Food",
  "Transport",
  "Bills",
  "Shopping",
  "Entertainment",
  "Others",
];

export const seedTransactions = [
  {
    id: "tx-001",
    date: "2026-01-02",
    title: "Freelance dashboard audit",
    amount: 12000,
    category: "Freelance",
    type: "income",
    note: "Client review and analytics cleanup",
  },
  {
    id: "tx-002",
    date: "2026-01-05",
    title: "Salary - January",
    amount: 74000,
    category: "Salary",
    type: "income",
    note: "Monthly salary credit",
  },
  {
    id: "tx-003",
    date: "2026-01-06",
    title: "Apartment rent",
    amount: 18800,
    category: "Housing",
    type: "expense",
    note: "Monthly rent payment",
  },
  {
    id: "tx-004",
    date: "2026-01-12",
    title: "Grocery basket",
    amount: 5200,
    category: "Food",
    type: "expense",
    note: "Kitchen restock and staples",
  },
  {
    id: "tx-005",
    date: "2026-01-17",
    title: "Metro recharge",
    amount: 2200,
    category: "Transport",
    type: "expense",
    note: "Monthly commute top-up",
  },
  {
    id: "tx-006",
    date: "2026-01-23",
    title: "Utility bills",
    amount: 3300,
    category: "Bills",
    type: "expense",
    note: "Electricity and broadband",
  },
  {
    id: "tx-007",
    date: "2026-01-29",
    title: "Weekend dinner",
    amount: 2400,
    category: "Entertainment",
    type: "expense",
    note: "Dining out and coffee catch-up",
  },
  {
    id: "tx-008",
    date: "2026-02-05",
    title: "Salary - February",
    amount: 75000,
    category: "Salary",
    type: "income",
    note: "Monthly salary credit",
  },
  {
    id: "tx-009",
    date: "2026-02-07",
    title: "Apartment rent",
    amount: 18800,
    category: "Housing",
    type: "expense",
    note: "Monthly rent payment",
  },
  {
    id: "tx-010",
    date: "2026-02-11",
    title: "Grocery shopping",
    amount: 5400,
    category: "Food",
    type: "expense",
    note: "Fresh groceries and home supplies",
  },
  {
    id: "tx-011",
    date: "2026-02-15",
    title: "Office commute",
    amount: 2300,
    category: "Transport",
    type: "expense",
    note: "Metro and cab travel",
  },
  {
    id: "tx-012",
    date: "2026-02-19",
    title: "Freelance UI sprint",
    amount: 14000,
    category: "Freelance",
    type: "income",
    note: "Design sprint delivery payout",
  },
  {
    id: "tx-013",
    date: "2026-02-22",
    title: "Utility bills",
    amount: 3500,
    category: "Bills",
    type: "expense",
    note: "Electricity and internet",
  },
  {
    id: "tx-014",
    date: "2026-02-27",
    title: "Festival shopping",
    amount: 4800,
    category: "Shopping",
    type: "expense",
    note: "Clothes and essentials",
  },
  {
    id: "tx-015",
    date: "2026-03-05",
    title: "Salary - March",
    amount: 76000,
    category: "Salary",
    type: "income",
    note: "Monthly salary credit",
  },
  {
    id: "tx-016",
    date: "2026-03-07",
    title: "Apartment rent",
    amount: 19000,
    category: "Housing",
    type: "expense",
    note: "Monthly rent payment",
  },
  {
    id: "tx-017",
    date: "2026-03-11",
    title: "Grocery and essentials",
    amount: 5600,
    category: "Food",
    type: "expense",
    note: "Bulk grocery restock",
  },
  {
    id: "tx-018",
    date: "2026-03-16",
    title: "Office commute",
    amount: 2400,
    category: "Transport",
    type: "expense",
    note: "Metro and cab travel",
  },
  {
    id: "tx-019",
    date: "2026-03-20",
    title: "Utility bills",
    amount: 3700,
    category: "Bills",
    type: "expense",
    note: "Electricity, internet, and water",
  },
  {
    id: "tx-020",
    date: "2026-03-23",
    title: "Online shopping",
    amount: 5200,
    category: "Shopping",
    type: "expense",
    note: "Workwear and daily essentials",
  },
  {
    id: "tx-021",
    date: "2026-03-28",
    title: "Freelance product revamp",
    amount: 16000,
    category: "Freelance",
    type: "income",
    note: "Design and development milestone",
  },
  {
    id: "tx-022",
    date: "2026-03-30",
    title: "Movie and dining",
    amount: 3200,
    category: "Entertainment",
    type: "expense",
    note: "Weekend plans",
  },
  {
    id: "tx-023",
    date: "2026-04-01",
    title: "Salary - April",
    amount: 78000,
    category: "Salary",
    type: "income",
    note: "Monthly salary credit",
  },
  {
    id: "tx-024",
    date: "2026-04-01",
    title: "Apartment rent",
    amount: 18500,
    category: "Housing",
    type: "expense",
    note: "Monthly rent payment",
  },
  {
    id: "tx-025",
    date: "2026-04-02",
    title: "Grocery restock",
    amount: 2350,
    category: "Food",
    type: "expense",
    note: "Fresh produce and essentials",
  },
  {
    id: "tx-026",
    date: "2026-04-02",
    title: "Metro recharge",
    amount: 1200,
    category: "Transport",
    type: "expense",
    note: "Commute balance top-up",
  },
  {
    id: "tx-027",
    date: "2026-04-02",
    title: "Electricity and internet",
    amount: 3200,
    category: "Bills",
    type: "expense",
    note: "Monthly utility payment",
  },
  {
    id: "tx-028",
    date: "2026-04-02",
    title: "Online shopping",
    amount: 4100,
    category: "Shopping",
    type: "expense",
    note: "Home and desk essentials",
  },
];
