export const LOCAL_STORAGE_KEY = "finance-dashboard-state-v2";
export const OPENING_BALANCE = 12850;

export const ROLE_OPTIONS = [
  { value: "viewer", label: "Viewer" },
  { value: "admin", label: "Admin" },
];

export const CATEGORY_OPTIONS = [
  "Salary",
  "Bonus",
  "Freelance",
  "Refund",
  "Housing",
  "Groceries",
  "Utilities",
  "Dining",
  "Entertainment",
  "Transport",
  "Travel",
  "Healthcare",
  "Shopping",
  "Education",
];

export const seedTransactions = [
  {
    id: "tx-001",
    date: "2025-11-01",
    title: "Monthly salary",
    amount: 4200,
    category: "Salary",
    type: "income",
    note: "Primary paycheck",
  },
  {
    id: "tx-002",
    date: "2025-11-02",
    title: "Apartment rent",
    amount: 1450,
    category: "Housing",
    type: "expense",
    note: "Downtown apartment",
  },
  {
    id: "tx-003",
    date: "2025-11-07",
    title: "Groceries",
    amount: 182,
    category: "Groceries",
    type: "expense",
    note: "Weekly essentials",
  },
  {
    id: "tx-004",
    date: "2025-11-14",
    title: "Consulting invoice",
    amount: 650,
    category: "Freelance",
    type: "income",
    note: "Landing page refresh",
  },
  {
    id: "tx-005",
    date: "2025-11-19",
    title: "Utilities",
    amount: 124,
    category: "Utilities",
    type: "expense",
    note: "Electricity and water",
  },
  {
    id: "tx-006",
    date: "2025-12-01",
    title: "Monthly salary",
    amount: 4200,
    category: "Salary",
    type: "income",
    note: "Primary paycheck",
  },
  {
    id: "tx-007",
    date: "2025-12-05",
    title: "Holiday flights",
    amount: 540,
    category: "Travel",
    type: "expense",
    note: "Round-trip tickets",
  },
  {
    id: "tx-008",
    date: "2025-12-11",
    title: "Dinner with friends",
    amount: 98,
    category: "Dining",
    type: "expense",
    note: "Year-end catch-up",
  },
  {
    id: "tx-009",
    date: "2025-12-15",
    title: "Dividend payout",
    amount: 140,
    category: "Refund",
    type: "income",
    note: "Brokerage distribution",
  },
  {
    id: "tx-010",
    date: "2025-12-22",
    title: "Holiday shopping",
    amount: 214,
    category: "Shopping",
    type: "expense",
    note: "Gifts and decor",
  },
];
